# Credentials for your Twitter bot account

CONSUMER_KEY = 'YOUR CREDENTIALS HERE'
CONSUMER_SECRET = 'YOUR CREDENTIALS HERE'

# Create a new Twitter Access Token
ACCESS_TOKEN = 'YOUR CREDENTIALS HERE' 
ACCESS_SECRET = 'YOUR CREDENTIALS HERE'

#PyOWM
OWM_KEY = 'YOUR CREDENTIALS HERE'

#511NY
NY511_KEY = 'YOUR CREDENTIALS HERE'